#!/bin/ksh

myusage() {
    echo "Usage: `basename $0` <target>"
    echo "  src         - checkout or update /usr/src"
    echo "  ports       - checkout or update /usr/ports"
    echo "  kernel      - build and install kernel"
    echo "  system      - build and install system"
    echo "  release     - build release files"
    exit 1
}

mysrc() {
    local _dir
    _dir="${1:-src}"

    SERVER="anoncvs@anoncvs.eu.openbsd.org:/cvs"
    BRANCH="${OPENBSD_BRANCH:-OPENBSD_`uname -r | tr . _`}"

    cd /usr || exit 1
    if [[ -d $_dir/CVS ]]; then
        cd $_dir && cvs -q up -r $BRANCH -Pd
    else
        cvs -qd $SERVER get -r $BRANCH -P $_dir
    fi
}

mykernel() {
    if [[ $(sysctl -n hw.ncpufound) -gt 1 ]]; then
        KERNEL=GENERIC.MP
    else
        KERNEL=GENERIC
    fi
    cd /usr/src/sys/arch/${MYARCH}/conf
    config ${KERNEL}
    cd /usr/src/sys/arch/${MYARCH}/compile/${KERNEL}
    make clean depend all install
}

mysystem() {
    cd /usr/obj && rm -fr *
    cd /usr/src && make obj
    cd /usr/src/etc && env DESTDIR=/ make distrib-dirs
    cd /usr/src && make build
}

myrelease() {
    MYDATE=`date +%Y%m%d`
    export DESTDIR="/var/tmp/dest-${MYDATE}/${MYARCH}"
    export RELEASEDIR="/var/tmp/release-${MYDATE}/${MYARCH}"

    [[ -d ${DESTDIR} ]] && rm -fr ${DESTDIR}
    [[ -d ${RELEASEDIR} ]] && rm -fr ${RELEASEDIR}
    mkdir -p ${DESTDIR} ${RELEASEDIR}
    cd /usr/src/distrib/special/libstubs && make obj depend all install
    cd /usr/src/etc && make release
    cd /usr/src/distrib/sets && sh checkflist
}

MYARCH=`uname -m`

umask 022

case $1 in
    src)
    mysrc src
    ;;

    ports)
    mysrc ports
    ;;

    kernel)
    mykernel
    ;;

    system)
    mysystem
    ;;

    release)
    myrelease
    ;;

    *)
    myusage
    ;;
esac
